package com.IcmcFileTracker.Views;

import com.IcmcFileTracker.model.Department;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.data.util.MethodProperty;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class DepartmentView extends CustomComponent implements View{
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private CheckBox edit;

	@AutoGenerated
	private Table table;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	BeanItemContainer<Department> beans = new BeanItemContainer<Department>(Department.class);
	
	public static final String VIEW_NAME = "DepartmentView";
	
	public DepartmentView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		table.setContainerDataSource(beans);
		table.setColumnCollapsingAllowed(true);
		table.setColumnReorderingAllowed(true);
		
		//edit = new CheckBox("Edit Departments", new MethodProperty<Boolean>(table, "editable"));
		
	}

	@Override
	public void enter(ViewChangeEvent event) {
		
		
		beans.removeAllItems();
		for(Department d: Department.getAll()){
			beans.addItem(d);
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		//mainLayout.set›mmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// table
		table = new Table();
		table.setCaption("Departments");
		//table.set›mmediate(false);
		table.setWidth("-1px");
		table.setHeight("-1px");
		//table.set›nvalidAllowed(false);
		mainLayout.addComponent(table);
		
		// edit
		edit = new CheckBox("Edit Departments", new MethodProperty<Boolean>(table, "editable"));
		//edit.setCaption("Edit Departments");
		edit.setImmediate(false);
		edit.setWidth("-1px");
		edit.setHeight("-1px");
		//edit.set›nvalidAllowed(false);
		mainLayout.addComponent(edit);
		
		return mainLayout;
	}

}
