package com.IcmcFileTracker.Views;

import com.IcmcFileTracker.Components.TracerTable;
import com.IcmcFileTracker.model.User;
import com.IcmcFileTracker.model.Tracer;
import com.IcmcFileTracker.model.TracerHead;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;

public class MyView extends CustomComponent implements View{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalSplitPanel verticalSplitPanel_2;
	@AutoGenerated
	private Table all;
	@AutoGenerated
	private Table owned;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	private final User user;
	
	public MyView(User user) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.user=user;
	
	}

	@Override
	public void enter(ViewChangeEvent event) {
		
		owned.removeAllItems();
		for(Tracer t : TracerHead.getByUser(user)){
			owned.addItem(t);
		}
		
		all.removeAllItems();
		for(Tracer t : Tracer.getByUser(user)){
			all.addItem(t);
		}
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		//mainLayout.set›mmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalSplitPanel_2
		verticalSplitPanel_2 = buildVerticalSplitPanel_2();
		mainLayout.addComponent(verticalSplitPanel_2);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalSplitPanel buildVerticalSplitPanel_2() {
		// common part: create layout
		verticalSplitPanel_2 = new VerticalSplitPanel();
		//verticalSplitPanel_2.set›mmediate(false);
		verticalSplitPanel_2.setWidth("-1px");
		verticalSplitPanel_2.setHeight("800px");
		
		// table_1
		owned = new TracerTable();
		//table_1.set›mmediate(false);
		owned.setWidth("-1px");
		owned.setHeight("-1px");
		//table_1.set›nvalidAllowed(false);
		verticalSplitPanel_2.addComponent(owned);
		
		// table_2
		all = new TracerTable();
		//table_2.set›mmediate(false);
		all.setWidth("-1px");
		all.setHeight("-1px");
		//table_2.set›nvalidAllowed(false);
		verticalSplitPanel_2.addComponent(all);
		
		return verticalSplitPanel_2;
	}

}
