package com.IcmcFileTracker.Components;

import com.IcmcFileTracker.IcmcFileTrackerUI;
import com.IcmcFileTracker.Forms.GenericForm;
import com.IcmcFileTracker.model.Department;
import com.IcmcFileTracker.model.LocalUser;
import com.IcmcFileTracker.model.Role;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class NavBar extends CustomComponent{

	private IcmcFileTrackerUI boss=null;
	private final VerticalLayout layout = new VerticalLayout();
	
	private MenuBar navBar = new MenuBar();
	
	
	Panel viewPannel = new Panel();
	
	
	public NavBar(IcmcFileTrackerUI mainUI ) {
		
		setCompositionRoot(layout);
		
		this.boss=mainUI;
		
		
		
		MenuBar.Command command = new MenuBar.Command() {	  
			private static final long serialVersionUID = 1L;

			public void menuSelected(MenuItem selected) {
				boss.navigator.navigateTo(selected.getText());
		    }  
		};
		
		
		//MenuItem home = navBar.addItem(HomeView.VIEW_NAME, null, command);
		//boss.navigator.addView(HomeView.VIEW_NAME, new HomeView());
		
		
		
		
		MenuItem home = navBar.addItem(TrackerHistory.VIEW_NAME, null, command);
		boss.navigator.addView(TrackerHistory.VIEW_NAME, new TrackerHistory());
		
		//MenuItem warn = navBar.addItem(TrackerWarning.VIEW_NAME, null, command);
		//boss.navigator.addView(TrackerWarning.VIEW_NAME, new TrackerWarning());
		
		
		MenuItem track = navBar.addItem(CreateTracker.VIEW_NAME, null, command);
		boss.navigator.addView(CreateTracker.VIEW_NAME, new CreateTracker(boss));
		
		/*
		track.addItem("All", null, command);
		track.addItem("CheckIN", null, command);
		track.addItem("CheckOUT", null, command);
		*/
		
		
		
		MenuItem userView = navBar.addItem(boss.user.getUserName(), null, command);
		boss.navigator.addView(boss.user.getUserName(), new CreateTracker(boss));
		
		
		MenuItem view = navBar.addItem("View", null, null);
		view.addItem("MyHistory", null, command);
		view.addItem("FileHistory", null, command);
		view.addItem("Warrnigs", null, command);
		view.addItem("CheckIns", null, command);
		view.addItem("CheckOuts", null, command);
		
		MenuItem admin = navBar.addItem("Admin", null, null);
		
		MenuItem create = admin.addItem("Create", null, null);
		create.addItem(Department.class.getSimpleName(), null, command);
		create.addItem(LocalUser.class.getSimpleName(), null, command);
		create.addItem(Role.class.getSimpleName(), null, command);
	

		MenuItem adminView = admin.addItem("View", null, null);
		adminView.addItem("Users", null, command);
		
		
		navBar.setSizeFull();
		layout.addComponent(navBar);
		layout.addComponent(viewPannel);
	}
}
