package com.IcmcFileTracker.Components;

import com.IcmcFileTracker.IcmcFileTrackerUI;
import com.IcmcFileTracker.Forms.GenericForm;
import com.IcmcFileTracker.Views.DepartmentView;
import com.IcmcFileTracker.Views.HomeView;
import com.IcmcFileTracker.Views.MyView;
import com.IcmcFileTracker.Views.TableExample;
import com.IcmcFileTracker.model.Department;
import com.IcmcFileTracker.model.User;
import com.IcmcFileTracker.model.Role;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class NavBar extends CustomComponent{

	private final VerticalLayout layout = new VerticalLayout();
	
	private MenuBar navBar = new MenuBar();
	private User user;
	private Navigator navigator;

	public NavBar(final Navigator navigator, final User user) {
		
		setCompositionRoot(layout);
		
		this.navigator=navigator;
		this.user=user;
			
		MenuBar.Command command = new MenuBar.Command() {	  
			private static final long serialVersionUID = 1L;

			public void menuSelected(MenuItem selected) {
				navigator.navigateTo(selected.getText());
		    }  
		};
		
		
		MenuItem home = navBar.addItem(HomeView.VIEW_NAME, null, command);
		navigator.addView(HomeView.VIEW_NAME, new HomeView());
	
		MenuItem track = navBar.addItem(CreateTracker.VIEW_NAME, null, command);
		navigator.addView(CreateTracker.VIEW_NAME, new CreateTracker(user));
		
		MenuItem fileView = navBar.addItem(TracerHistory.VIEW_NAME, null, command);
		navigator.addView(TracerHistory.VIEW_NAME, new TracerHistory());
		
		MenuItem userView = navBar.addItem(user.getUserName(), null, command);
		navigator.addView(user.getUserName(), new MyView(user));
		
	
		MenuItem temp = navBar.addItem("temp", null, command);
		navigator.addView("temp", new TableExample());
	
		MenuItem admin = navBar.addItem("Admin", null, null);
		
		MenuItem create = admin.addItem(DepartmentView.VIEW_NAME, null, command);
		navigator.addView(DepartmentView.VIEW_NAME, new DepartmentView());
		/*
		MenuItem create = admin.addItem("New", null, null);
		create.addItem(User.class.getSimpleName(), null, command);
		create.addItem(Department.class.getSimpleName(), null, command);
		
		MenuItem adminView = admin.addItem("View", null, null);
		adminView.addItem(User.class.getSimpleName(), null, command);
		adminView.addItem(Department.class.getSimpleName(), null, command);
		*/
		
		//navBar.setSizeFull();
		navBar.setSizeUndefined();
		layout.addComponent(navBar);
	}
}