package com.IcmcFileTracker.Components;

import com.IcmcFileTracker.model.FileTracker;
import com.IcmcFileTracker.model.Tracker;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class TrackerHistory extends CustomComponent implements View{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table table;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	public static final String VIEW_NAME ="TrackerHistory";
	
	BeanItemContainer<Tracker> beans = new BeanItemContainer<Tracker>(Tracker.class);
	
	public TrackerHistory() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		table.setContainerDataSource(beans);
		table.setColumnCollapsingAllowed(true);
		table.setColumnReorderingAllowed(true);
		
		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		//mainLayout.set›mmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// table
		table = new Table();
		table.setCaption("Recent Tracker History");
		//table.set›mmediate(false);
		table.setWidth("-1px");
		table.setHeight("-1px");
		//table.set›nvalidAllowed(false);
		mainLayout.addComponent(table);
		
		return mainLayout;
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
		beans.removeAllItems();
		for(Tracker t : FileTracker.getAllLatestTrackers()){
			beans.addItem(t);
		}
	}

}
