package com.IcmcFileTracker.Components;

import java.util.List;

import com.IcmcFileTracker.model.FileTracker;
import com.IcmcFileTracker.model.Tracker;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Component.Listener;

public class TrackerWarning extends CustomComponent implements View, Listener{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout warning_links;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private NativeSelect days;
	@AutoGenerated
	private Label label_1;
	private static final long serialVersionUID = 1L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	public static final String VIEW_NAME ="TrackerWarnings";
	
	public TrackerWarning() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		
		Object selected = new Integer(1);
		days.addItem(selected) ;
		days.addItem(new Integer(2));
		days.addItem(new Integer(3));
		days.select(selected);
		
		days.addListener(this);
	}

	@Override
	public void enter(ViewChangeEvent event) {
		update();
	}
	
	@Override
	public void componentEvent(Event event) {
		update();
	}
	
	private void update(){
		warning_links.removeAllComponents();
		
		int dayInt = ((Integer)days.getValue()).intValue();
		
		List<Tracker> l = FileTracker.getOldTrackers(dayInt);
		
		warning_links.addComponent(new Label(l.size()+" Trackers older than "+dayInt+" days"));
		
		for(Tracker t : l){
			warning_links.addComponent(new Label(t.toString()));
		}
	}
	
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// warning_links
		warning_links = new VerticalLayout();
		warning_links.setCaption("");
		warning_links.setImmediate(false);
		warning_links.setWidth("-1px");
		warning_links.setHeight("-1px");
		warning_links.setMargin(false);
		mainLayout.addComponent(warning_links);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(true);
		horizontalLayout_1.setSpacing(true);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Files Checked Out for more than");
		horizontalLayout_1.addComponent(label_1);
		
		// days
		days = new NativeSelect();
		days.setImmediate(true);
		days.setWidth("-1px");
		days.setHeight("-1px");
		days.setInvalidAllowed(false);
		horizontalLayout_1.addComponent(days);
		horizontalLayout_1.setComponentAlignment(days, new Alignment(9));
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Days");
		horizontalLayout_1.addComponent(label_2);
		
		return horizontalLayout_1;
	}
}
